server.port=8085
server.servlet.context-path=/story

# MongoDB Config
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=notification-service
spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.authentication-database=admin

cloudflare.r2.account-id=48939836611954ff55096968a8998270
cloudflare.r2.access-key=1e035a526d6ad3a7bd0ffaa7149d0315
cloudflare.r2.secret-key=53bd333daaceba50eaabe22c0b0879ef35a3e238ade57085d3eaa808dc2398b0
cloudflare.r2.bucket-name=stories-bucket
cloudflare.r2.public-url=https://pub-5ca1c81f3ae34d04ac4c73a6aeacc4f7.r2.dev

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=120MB

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=root

app.services.identity = http://localhost:8080/identity/user