server.port=8084
server.servlet.context-path=/post
spring.application.name=PostService
spring.datasource.url=jdbc:postgresql://localhost:5433/post
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

cloudflare.r2.account-id=b20f665521d7494d518f301821cfceb8
cloudflare.r2.access-key=84bfde63d1eaf0278cb6c28e0a4f4fab
cloudflare.r2.secret-key=a1c1ea67c4b37b1b777438d2d2a542b343c5b88077d20fdb5a810c7347ff5e61
cloudflare.r2.bucket-name=post
cloudflare.r2.public-url=https://b20f665521d7494d518f301821cfceb8.r2.cloudflarestorage.com

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=700MB

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
